try:

    print(x)

except NameError:
    print("Encontramos um erro e jรก estamos resolvendo isso")